### ISSUE TITLE
No isort python module detected, you should install it. More info at https://github.com/fisadev/vim-iso rt

### ISSUE THREAD

**Issue by zatan** [fisadev/vim-isort#14]
Hi,

I have installed `isort` globally with `pip install isort` but whatever I try to use it gives me the error above.

**Comment by fisadev** [comment]
Hey, sorry for the lack of response, I had a very complicated pair of weeks (including trips).

Did you find the solution? what was the problem? There are a set of common scenarios related to this error (virtualenvs and neovim, python3 vs python2, and some weird issues with mac os)

**Comment by zatan** [comment]
Hey,

The problem was I used `pip` to install the `isort` into `virtualenv`, but `VIM` wasn't picking the `isort` from the `virtualenv`.

Then I tried to install `isort` globally, but this didn't work either because by typing `pip --version` gives this output that my `pip` uses `python3.5` :

```
pip 8.1.2 from /usr/local/lib/python3.5/dist-packages/pip-8.1.2-py3.5.egg (python 3.5)
```
My `VIM` doesn't support `python3` (you can find this by typing `vim --version`) so it didn't work again, the solution was to use `pip2.7` to install `isort`.

```
pip2.7 install isort
```

I hope this helps and can be added to the docs.

**Comment by fisadev** [comment]
Thanks for the details! Yes, I must clarify this in the docs.

**Comment by zsoobhan** [comment]
I had a similar issue which `vim-sort` could not find `isort` even though it was installed globally and in the `virtualenv`.

I had to find the actual python binary vim was using and install it in there.

1. in vim 
`:py3 import sys; print(sys.path)`

2. navigate to that location and find the python binary, in my case: 
`cd /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/bin`

3. install isort using this binary
`python3.8 -m pip install isort`

I am using pyenv and virtualenv which may have messed up my paths and for some reason vim-isort could not find the "correct" python version when using `:py3` at https://github.com/fisadev/vim-isort/blob/master/ftplugin/python_vimisort.vim#L12.
