### ISSUE TITLE
Cursor jumps to the first line after sorting

### ISSUE THREAD

**Issue by yevhen-m** [fisadev/vim-isort#15]
After I sort imports, cursor jumps to the first line. Is it possible to put it back after sorting where it was before sorting?

**Comment by yevhen-m** [comment]
Thanks, no longer have this issue.

**Comment by im-n1** [comment]
I'm facing this issue. How did u @yevhen-m solved this?

**Comment by tgy** [comment]
same. this should be re-opened

**Comment by rronan** [comment]
I face the same issue.

I happens only with multi-line imports: e.g., I import several variables from one module, line is too long and splitted in multiple lines.

I think it should be re-opened

**Comment by rronan** [comment]
```let g:vim_isort_config_overrides = {'multi_line_output': 3}``` seems to work

(it changes the format of multi line imports but that's fine with me, at least)

**Comment by tgy** [comment]
thanks, i'm running `black` right after `isort` so i don't really care about `isort`'s formatting 😄

**Comment by patroqueeet** [comment]
@rronan did help for me with black/isort...
