### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ipkiss42** [fisadev/vim-isort#30]
Hi,

I would like to use your plugin, but it is currently missing a license. I suspect you intended your code to be used under the MIT license ([like isort itself](https://github.com/timothycrosley/isort/blob/develop/LICENSE)) or the Vim license, but it would be nice to make it explicit with a LICENSE file :)

Thanks in advance!

**Comment by fisadev** [comment]
You are right, adding it. Really sorry for the time this has been dead, personal things getting in the way of me contributing too much to OSS. Getting back to it :)

**Comment by fisadev** [comment]
Done!
