### ISSUE TITLE
Isort occasionally puts blank line at end of file

### ISSUE THREAD

**Issue by benbarbour** [fisadev/vim-isort#6]
Then pylint complains.

**Comment by fisadev** [comment]
ups, I have to look into it, thanks for reporting the issue

**Comment by fisadev** [comment]
Adding more info to this: not only the line at the end, but also sometimes it deletes the mandatory 2 empty lines between imports and the rest of the code (pep8), leaving only one line.

**Comment by w0rp** [comment]
:+1: to this. I keep getting blank lines now and again, which I have to go and then fix.

**Comment by fisadev** [comment]
A new fix was pushed to master. Can you check if it works? :)

**Comment by w0rp** [comment]
Sorry for no updates on this. I'll check this if I ever find the time.

**Comment by benbarbour** [comment]
Seems OK at first blush. Thanks!

Of course, it was intermittent to begin with. I'll keep using it though and if you close this issue it can always be re-opened if it happens again.

**Comment by fisadev** [comment]
Ok! I'll close it then, and let me know if it comes back again.
